sudo: required
services: 
  - docker
before_install:
  - docker build -t MSaqibBhatti/docker-react -f Dockerfile.dev Dockerfile.dev

script:
  - docker run -e CI=true MSaqibBhatti/docker-react npm run test 

language: generic